### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by GeoTuxMan** [slucey/RpathDev#1]
Hello !

I want to start to work(to play first :)) with Rpath, and I have 2 issues:
1)I try to install Rpath:
`> library(devtools)

> devtools::install_github('slucey/RpathDev/Rpath', build_vignettes = TRUE)
> Downloading GitHub repo slucey/RpathDev@master
> from URL https://api.github.com/repos/slucey/RpathDev/zipball/master
> Error in download(dest, src, auth) : Not Found (HTTP 404).`

2) If I have this data in EwE:
Group name: turbot1, turbot2,turbot3,turbo4,turbot5,turbot6,turbot7,turbot8,turbot9(leading)
Age: 0,12,24,36,48,60,72,84,96
Biomass: 11.10,39.06,91.12,144.71,134.56,92.86,55.00,30.54,32.40
Z: 3,0.8,0.1,0.5,0.7,0.8,0.8,0.8,0.8
Consumption/biomass: 13.00,5.50,3.58,2.81,2.38,2.10,1.92,1.79,1.64,
how do I write/change the R script :
`
groups <- c('Seabirds', 'Whales', 'Seals', 'JuvRoundfish1', 'AduRoundfish1', 
            'JuvRoundfish2', 'AduRoundfish2', 'JuvFlatfish1', 'AduFlatfish1',
            'JuvFlatfish2', 'AduFlatfish2', 'OtherGroundfish', 'Foragefish1',
            'Foragefish2', 'OtherForagefish', 'Megabenthos', 'Shellfish',
            'Macrobenthos', 'Zooplankton', 'Phytoplankton', 'Detritus', 
            'Discards', 'Trawlers', 'Midwater', 'Dredgers')
stgroups <- c(rep(NA, 3), rep('Roundfish1', 2), rep('Roundfish2', 2), 
              rep('Flatfish1', 2), rep('Flatfish2', 2), rep(NA, 14))

types  <- c(rep(0, 19), 1, rep(2, 2), rep(3, 3))
# -------------------------------------------------------------------------------
# Create Model File

REco.params <- create.rpath.param(group = groups, type = types, stgroup = stgroups,
                                  nstanzas = rep(2,4))
# Fill appropriate columns
# Model

biomass <- c(0.0149, 0.454, NA, NA, 1.39, NA, 5.553, NA, 5.766, NA,
             0.739, 7.4, 5.1, 4.7, 5.1, NA, 7, 17.4, 23, 10, rep(NA, 5))

pb <- c(0.098, 0.031, 0.100, 2.026, 0.42, 2.1, 0.425, 1.5, 0.26, 1.1, 0.18, 0.6,
        0.61, 0.65, 1.5, 0.9, 1.3, 7, 39, 240, rep(NA, 5))

qb <- c(76.750, 6.976, 34.455, NA, 2.19, NA, 3.78, NA, 1.44, NA, 1.69,
        1.764, 3.52, 5.65, 3.6, 2.984, rep (NA, 9))

REco.params$model[, Biomass := biomass]
REco.params$model[, PB := pb]
REco.params$model[, QB := qb] `

Thank you very much in advance !
George

**Comment by slucey** [comment]
Dear George,

Sorry for the tardy response.  I was at sea with temperamental internet
access.  The issue with connecting is because the RpathDev repository does
not sit on the "Master" branch.  Rather it sits on a branch names
"Public".  It was a naming convention that simplified things for me but has
created a lot of confusion from users like yourself trying to download it.
To download the code add the follow argument to the install_github
command: *ref
= 'Public'.  *Please note that some people have been having issues with the
vignettes due to issues with their pandoc library.

The second issue looks like you are trying to add a multistanza group.  You
would add them similar to the way that the juvenile and adult groups are
added below.  However, you should only add the biomass and consumption for
the leading stanza and allow the function rpath.stanzas() calculate the
trailing biomasses and consumptions.

Let me know if you have any further questions.

Sean

Sean M. Lucey
Fisheries Biologist
U. S. Dept. of Commerce/NOAA/NMFS
Northeast Fisheries Science Center
166 Water Street, Woods Hole, MA 02543
508-495-2011 (voice)
508-495-2232 (fax)

**Comment by GeoTuxMan** [comment]
Dear Sean,

Thanks for your reply, it's really help me.
I install RPath; it was need to install Rtools and rmarkdown before.
Regarding my R script, I don't have time in this period, to rewrite the
script; so we'll discuss later about that.

Cheers !
George

2016-05-16 16:24 GMT+03:00 Sean Lucey notifications@github.com:
